Repository Special-Kode/College-and-Deans, pull requests merged in 2021-12, with the labels that each got.

#179 Adding rooms to room generation
  College and Deans/Assets/Resources/Rooms/Room_04/Room_BL_04.prefab
  College and Deans/Assets/Resources/Rooms/Room_04/Room_B_04.prefab
  College and Deans/Assets/Resources/Rooms/Room_04/Room_L_04.prefab
  College and Deans/Assets/Resources/Rooms/Room_04/Room_RBL_04.prefab
  College and Deans/Assets/Resources/Rooms/Room_04/Room_RB_04.prefab
  College and Deans/Assets/Resources/Rooms/Room_04/Room_RL_04.prefab
  College and Deans/Assets/Resources/Rooms/Room_04/Room_R_04.prefab
  College and Deans/Assets/Resources/Rooms/Room_04/Room_TBL_04.prefab
  College and Deans/Assets/Resources/Rooms/Room_04/Room_TB_04.prefab
  College and Deans/Assets/Resources/Rooms/Room_04/Room_TL_04.prefab
  College and Deans/Assets/Resources/Rooms/Room_04/Room_TRBL_04.prefab
  College and Deans/Assets/Resources/Rooms/Room_04/Room_TRB_04.prefab
  College and Deans/Assets/Resources/Rooms/Room_04/Room_TRL_04.prefab
  College and Deans/Assets/Resources/Rooms/Room_04/Room_TR_04.prefab
  College and Deans/Assets/Resources/Rooms/Room_04/Room_T_04.prefab
  College and Deans/Assets/Resources/Rooms/Room_05/Room_BL_05.prefab
  College and Deans/Assets/Resources/Rooms/Room_05/Room_B_05.prefab
  College and Deans/Assets/Resources/Rooms/Room_05/Room_L_05.prefab
  College and Deans/Assets/Resources/Rooms/Room_05/Room_RBL_05.prefab
  College and Deans/Assets/Resources/Rooms/Room_05/Room_RB_05.prefab
  College and Deans/Assets/Resources/Rooms/Room_05/Room_RL_05.prefab
  College and Deans/Assets/Resources/Rooms/Room_05/Room_R_05.prefab
  College and Deans/Assets/Resources/Rooms/Room_05/Room_TBL_05.prefab
  College and Deans/Assets/Resources/Rooms/Room_05/Room_TBL_05.prefab.meta
  College and Deans/Assets/Resources/Rooms/Room_05/Room_TB_05.prefab
  College and Deans/Assets/Resources/Rooms/Room_05/Room_TL_05.prefab
  College and Deans/Assets/Resources/Rooms/Room_05/Room_TRBL_05.prefab
  College and Deans/Assets/Resources/Rooms/Room_05/Room_TRB_05.prefab
  College and Deans/Assets/Resources/Rooms/Room_05/Room_TRL_05.prefab
  College and Deans/Assets/Resources/Rooms/Room_05/Room_TR_05.prefab
  College and Deans/Assets/Resources/Rooms/Room_05/Room_T_05.prefab
  College and Deans/Assets/Resources/Rooms/Room_06/Room_BL_06.prefab
  College and Deans/Assets/Resources/Rooms/Room_06/Room_B_06.prefab
  College and Deans/Assets/Resources/Rooms/Room_06/Room_L_06.prefab
  College and Deans/Assets/Resources/Rooms/Room_06/Room_RBL_06.prefab
  College and Deans/Assets/Resources/Rooms/Room_06/Room_RB_06.prefab
  College and Deans/Assets/Resources/Rooms/Room_06/Room_RL_06.prefab
  College and Deans/Assets/Resources/Rooms/Room_06/Room_R_06.prefab
  College and Deans/Assets/Resources/Rooms/Room_06/Room_TBL_06.prefab
  College and Deans/Assets/Resources/Rooms/Room_06/Room_TB_06.prefab
  College and Deans/Assets/Resources/Rooms/Room_06/Room_TL_06.prefab
  College and Deans/Assets/Resources/Rooms/Room_06/Room_TRBL_06.prefab
  College and Deans/Assets/Resources/Rooms/Room_06/Room_TRBL_06.prefab.meta
  College and Deans/Assets/Resources/Rooms/Room_06/Room_TRB_06.prefab
  College and Deans/Assets/Resources/Rooms/Room_06/Room_TRL_06.prefab
  College and Deans/Assets/Resources/Rooms/Room_06/Room_TRL_06.prefab.meta
  College and Deans/Assets/Resources/Rooms/Room_06/Room_TR_06.prefab
  College and Deans/Assets/Resources/Rooms/Room_06/Room_T_06.prefab
  College and Deans/Assets/Scripts/RoomGeneration/DungeonGeneratorManager.cs
  College and Deans/Assets/Sprites/Candado.png.meta
  College and Deans/Assets/Sprites/Tablones.png.meta
  College and Deans/Assets/Sprites/Tablones_cruzados.png.meta
Labels: enhancement, level design, room generation

#184 Time stops when player touches the stairs
  College and Deans/Assets/Prefabs/Props/Stairs_up.prefab
  College and Deans/Assets/Scripts/PlayerMechanics/ExternMechanicsPlayer.cs
  College and Deans/Assets/Scripts/RoomGeneration/StairsBehaviour.cs
Labels: fix, player control, level transition

#188 Added picked up items on GUI
  College and Deans/Assets/Prefabs/Canvas.prefab
  College and Deans/Assets/Prefabs/UI.meta
  College and Deans/Assets/Prefabs/UI/ItemImage.prefab
  College and Deans/Assets/Prefabs/UI/ItemImage.prefab.meta
  College and Deans/Assets/Scenes/SampleScene.unity
  College and Deans/Assets/Scripts/Inventory.cs
  College and Deans/Assets/Scripts/Inventory.cs.meta
  College and Deans/Assets/Scripts/Items/ConsumableItem.cs
  College and Deans/Assets/Scripts/Items/ModifierItem.cs
  College and Deans/Assets/Scripts/Managers/StatsManager.cs
  College and Deans/Assets/Sprites/UI/ItemsUI.png
  College and Deans/Assets/Sprites/UI/ItemsUI.png.meta
Labels: enhancement, UI

#191 Fixed Dash on Pause
  College and Deans/Assets/Prefabs/Bomb.prefab
  College and Deans/Assets/Scripts/PlayerMechanics/AnimatorPlayerScript.cs
  College and Deans/Assets/Scripts/PlayerMechanics/Modifiers.cs
  College and Deans/UserSettings/EditorUserSettings.asset
Labels: fix, player control

#192 Added padlock sprite rotation
  College and Deans/Assets/Scripts/OtherBehaviours/DoorBehaviour.cs
Labels: enhancement, room generation

#193 Fixed minor bugs
  College and Deans/Assets/Prefabs/Canvas.prefab
  College and Deans/Assets/Resources/Rooms/Room_04/Room_TB_04.prefab
  College and Deans/Assets/Resources/Rooms/Room_06/Room_TB_06.prefab
  College and Deans/Assets/Scenes/MainMenu.unity
  College and Deans/Assets/Scenes/SampleScene.unity
  College and Deans/Assets/Scripts/Enemy/Boss/BossIA.cs
  College and Deans/Assets/Scripts/Enemy/Boss/Boss_2_IA.cs
  College and Deans/Assets/Scripts/Enemy/EnemyPathfinding.cs
  College and Deans/Assets/Scripts/PlayerMechanics/AttackBehaviour.cs
  College and Deans/ProjectSettings/ProjectSettings.asset
  College and Deans/UserSettings/EditorUserSettings.asset
Labels: fix

#194 Fixed some UI minor issues
  College and Deans/Assets/Scenes/SampleScene.unity
  College and Deans/ProjectSettings/ProjectSettings.asset
  College and Deans/ProjectSettings/UnityConnectSettings.asset
Labels: fix, menu, UI

#197 07 Room batch
  College and Deans/Assets/Resources/Rooms/Room_07.meta
  College and Deans/Assets/Resources/Rooms/Room_07/Room_BL_07.prefab
  College and Deans/Assets/Resources/Rooms/Room_07/Room_BL_07.prefab.meta
  College and Deans/Assets/Resources/Rooms/Room_07/Room_B_07.prefab
  College and Deans/Assets/Resources/Rooms/Room_07/Room_B_07.prefab.meta
  College and Deans/Assets/Resources/Rooms/Room_07/Room_L_07.prefab
  College and Deans/Assets/Resources/Rooms/Room_07/Room_L_07.prefab.meta
  College and Deans/Assets/Resources/Rooms/Room_07/Room_RBL_07.prefab
  College and Deans/Assets/Resources/Rooms/Room_07/Room_RBL_07.prefab.meta
  College and Deans/Assets/Resources/Rooms/Room_07/Room_RB_07.prefab
  College and Deans/Assets/Resources/Rooms/Room_07/Room_RB_07.prefab.meta
  College and Deans/Assets/Resources/Rooms/Room_07/Room_RL_07.prefab
  College and Deans/Assets/Resources/Rooms/Room_07/Room_RL_07.prefab.meta
  College and Deans/Assets/Resources/Rooms/Room_07/Room_R_07.prefab
  College and Deans/Assets/Resources/Rooms/Room_07/Room_R_07.prefab.meta
  College and Deans/Assets/Resources/Rooms/Room_07/Room_TBL_07.prefab
  College and Deans/Assets/Resources/Rooms/Room_07/Room_TBL_07.prefab.meta
  College and Deans/Assets/Resources/Rooms/Room_07/Room_TB_07.prefab
  College and Deans/Assets/Resources/Rooms/Room_07/Room_TB_07.prefab.meta
  College and Deans/Assets/Resources/Rooms/Room_07/Room_TL_07.prefab
  College and Deans/Assets/Resources/Rooms/Room_07/Room_TL_07.prefab.meta
  College and Deans/Assets/Resources/Rooms/Room_07/Room_TRBL_07.prefab
  College and Deans/Assets/Resources/Rooms/Room_07/Room_TRBL_07.prefab.meta
  College and Deans/Assets/Resources/Rooms/Room_07/Room_TRB_07.prefab
  College and Deans/Assets/Resources/Rooms/Room_07/Room_TRB_07.prefab.meta
  College and Deans/Assets/Resources/Rooms/Room_07/Room_TRL_07.prefab
  College and Deans/Assets/Resources/Rooms/Room_07/Room_TRL_07.prefab.meta
  College and Deans/Assets/Resources/Rooms/Room_07/Room_TR_07.prefab
  College and Deans/Assets/Resources/Rooms/Room_07/Room_TR_07.prefab.meta
  College and Deans/Assets/Resources/Rooms/Room_07/Room_T_07.prefab
  College and Deans/Assets/Resources/Rooms/Room_07/Room_T_07.prefab.meta
Labels: enhancement, level design

#198 Added more rooms to room generation
  College and Deans/Assets/Resources/Rooms/Room_Pow/Room_Pow_B.prefab
  College and Deans/Assets/Resources/Rooms/Room_Pow/Room_Pow_BL.prefab
  College and Deans/Assets/Resources/Rooms/Room_Pow/Room_Pow_L.prefab
  College and Deans/Assets/Resources/Rooms/Room_Pow/Room_Pow_R.prefab
  College and Deans/Assets/Resources/Rooms/Room_Pow/Room_Pow_RB.prefab
  College and Deans/Assets/Resources/Rooms/Room_Pow/Room_Pow_RBL.prefab
  College and Deans/Assets/Resources/Rooms/Room_Pow/Room_Pow_RL.prefab
  College and Deans/Assets/Resources/Rooms/Room_Pow/Room_Pow_T.prefab
  College and Deans/Assets/Resources/Rooms/Room_Pow/Room_Pow_TB.prefab
  College and Deans/Assets/Resources/Rooms/Room_Pow/Room_Pow_TBL.prefab
  College and Deans/Assets/Resources/Rooms/Room_Pow/Room_Pow_TL.prefab
  College and Deans/Assets/Resources/Rooms/Room_Pow/Room_Pow_TR.prefab
  College and Deans/Assets/Resources/Rooms/Room_Pow/Room_Pow_TRB.prefab
  College and Deans/Assets/Resources/Rooms/Room_Pow/Room_Pow_TRBL.prefab
  College and Deans/Assets/Resources/Rooms/Room_Pow/Room_Pow_TRL.prefab
  College and Deans/Assets/Scripts/OtherBehaviours/MinimapRoomBehaviour.cs
  College and Deans/Assets/Scripts/RoomGeneration/DungeonGeneratorManager.cs
Labels: enhancement, room generation

#199 New sprites for power ups + item outlines added
  College and Deans/Assets/Sprites/bm_icon_spritesheet.png
Labels: enhancement, art design

#201 WASD move icon
  College and Deans/Assets/Sprites/Controls/pc_move_EN.png
  College and Deans/Assets/Sprites/Controls/pc_move_ES.png
Labels: enhancement, art design

#202 Fixed boss not being damaged by waves
  College and Deans/Assets/Prefabs/Boss 0.prefab
  College and Deans/Assets/Prefabs/Boss 1.prefab
Labels: fix, npc behaviour

#203 Adding damage animation to entities
  College and Deans/Assets/Scripts/Enemy/Enemy.cs
  College and Deans/Assets/Scripts/PlayerMechanics/ExternMechanicsPlayer.cs
Labels: enhancement, player control, npc behaviour

#204 Fixed some rooms not detecting holes
  College and Deans/Assets/Resources/Rooms/Room_04/Room_L_04.prefab
  College and Deans/Assets/Resources/Rooms/Room_04/Room_RBL_04.prefab
  College and Deans/Assets/Resources/Rooms/Room_04/Room_TBL_04.prefab
  College and Deans/Assets/Resources/Rooms/Room_04/Room_TRB_04.prefab
  College and Deans/Assets/Resources/Rooms/Room_04/Room_TRL_04.prefab
  College and Deans/Assets/Resources/Rooms/Room_06/Room_TRB_06.prefab
  College and Deans/Assets/Resources/Rooms/Room_06/Room_TRL_06.prefab
Labels: level design, fix, room generation

#207 Adjust menu modifiers
  College and Deans/Assets/Resources/Items/CafeItems/CookieJar.asset
  College and Deans/Assets/Resources/Items/CafeItems/MondayMenu.asset
  College and Deans/Assets/Resources/Items/CafeItems/TuesdayMenu.asset
  College and Deans/Assets/Resources/Items/Enhancers/Pressonesso.asset
  College and Deans/Assets/Resources/Items/Enhancers/Ualium.asset
  College and Deans/Assets/Scripts/PlayerMechanics/AnimatorPlayerScript.cs
  College and Deans/Assets/Scripts/PlayerMechanics/Weapon.cs
Labels: fix, items

#208 Added stats display to UI
  College and Deans/Assets/Prefabs/Canvas.prefab
  College and Deans/Assets/Scripts/UIBehaviours/StatsDisplay.cs
  College and Deans/Assets/Scripts/UIBehaviours/StatsDisplay.cs.meta
  College and Deans/Assets/Sprites/UI/Damage.png
  College and Deans/Assets/Sprites/UI/Damage.png.meta
  College and Deans/Assets/Sprites/UI/Resistance.png
  College and Deans/Assets/Sprites/UI/Resistance.png.meta
  College and Deans/Assets/Sprites/UI/Speed.png
  College and Deans/Assets/Sprites/UI/Speed.png.meta
  College and Deans/Assets/Sprites/UI/Timescale.png
  College and Deans/Assets/Sprites/UI/Timescale.png.meta
Labels: enhancement, UI

#210 Fixed minor bugs
  College and Deans/Assets/Scenes/SampleScene.unity
  College and Deans/Assets/Scripts/UIBehaviours/StatsDisplay.cs
  College and Deans/ProjectSettings/NavMeshAreas.asset
Labels: fix

#211 Fix balance enemies
  College and Deans/Assets/Prefabs/Boss 0.prefab
  College and Deans/Assets/Prefabs/Boss 1.prefab
  College and Deans/Assets/Prefabs/Enemy_Distancia_1.prefab
  College and Deans/Assets/Prefabs/Enemy_Distancia_2.prefab
  College and Deans/Assets/Prefabs/Enemy_Melee_1.prefab
  College and Deans/Assets/Resources/Items/CafeItems/FridayMenu.asset
  College and Deans/Assets/Scripts/Enemy/Enemy.cs
  College and Deans/Assets/Scripts/OtherBehaviours/Collisions.cs
  College and Deans/Assets/Scripts/PlayerMechanics/AnimatorPlayerScript.cs
  College and Deans/Assets/Scripts/PlayerMechanics/Weapon.cs
  College and Deans/Assets/Scripts/RoomGeneration/DungeonGeneratorManager.cs
Labels: fix, npc behaviour
